### ISSUE TITLE
Piscem map fails with error - fatal runtime error: Rust cannot catch foreign exceptions - when executed within AWS Lambda.

### ISSUE THREAD

**Issue by nihanasam8** [COMBINE-lab/piscem#24]
Hi Team,

I have created a container that runs piscem-map. I am able to run the container in my ubuntu instance. However when I run the container in AWS Lambda, it fails with an error - fatal runtime error: Rust cannot catch foreign exceptions.

Based on my observation, since Piscem successfully loaded the index, it appears that the Piscem executable itself is functioning correctly. I've created a custom base image, compiled the Piscem repository, and transferred its executable to the local bin directory.

Could you please let us know if there are any additional dependencies necessary for piscem map to be successful.

Below is the output in AWS Lambda:
```
[2m2024-07-05T00:28:50.232239Z[0m [32m INFO[0m [2mpiscem[0m[2m:[0m cmd: ["sc_ref_mapper", "-i", "/var/task/index_output_transcriptome/index_output_transcriptome", "-g", "chromium_v3", "-1", "/var/task/fastq/pbmc_1k_v3_S1_L001_R1_001_1.fastq,/var/task/fastq/pbmc_1k_v3_S1_L002_R1_001_1.fastq", "-2", "/var/task/fastq/pbmc_1k_v3_S1_L001_R2_001_1.fastq,/var/task/fastq/pbmc_1k_v3_S1_L002_R2_001_1.fastq", "-t", "2", "-o", "/var/task/output/split_map_output_transcriptome", "--max-ec-card", "4096", "--skipping-strategy", "permissive", "--max-hit-occ", "256", "--max-hit-occ-recover", "1024", "--max-read-occ", "2500"]

[2024-07-05 00:28:50.233] [info] enable structural constraints : false
[2024-07-05 00:28:50.234] [info] No poison k-mer map exists, or it was requested not to be used
[2024-07-05 00:28:50.234] [info] loading index from /var/task/index_output_transcriptome/index_output_transcriptome
[2024-07-05 00:28:51.877] [info] done loading index
fatal runtime error: Rust cannot catch foreign exceptions
```
Thanks,
Niharika

**Comment by rob-p** [comment]
Hi @nihanasam8,

  This is a tough one since it only shows up when running on a lambda instance and since we don’t have any more debugging information.  I’m not super familiar with lambda, but one hypothesis is the following.

  When `piscem` is compiled, it checks about the capabilities of the processor on the system, and enables / disables some command line flags based on those capabilities (e.g. advanced bit manipulation instructions that make some things faster).  It’s possible that some flags are enabled on the machine doing the compiling that are not available on the lambda instance.  Would it be possible to either *compile* the program on a lambda and see if that runs or explicitly disable features in the `CMake` file that may not be supported on processors powering lambda instances?

Best,
Rob

**Comment by nihanasam8** [comment]
Hi @rob-p,

I tried to run piscem using the binary and also ran it by compiling from source code.In both the scenarios, I'm facing the same issue. Could you please provide more information about the flags that needs to be enabled/disabled for piscem to function properly?

Thanks,
Niharika

**Comment by rob-p** [comment]
Hi @nihanasam8,

  Can you say anything about the specific data on which you are observing this behavior?  Also, if you have a chance can you please make sure you are using the latest release of `piscem` - we fixed a rare but in the most recent release.  The most relevant feature is the BMI2 instruction set. That should be on almost all recent CPUs, but I don't know what the lambda instances run.  You can try building with `CONDA_BUILD=TRUE NO_BMI2=TRUE cargo build --release`, and see if that behaves any differently.

Best,
Rob

**Comment by nihanasam8** [comment]
Hi Rob,

I have compiled piscem with NO_BMI2=TRUE and NO_SIMD=True. I'm still facing the same issue when I run piscem on lambda. I have reached out to AWS support team and currently awaiting their response.

Thanks,
Niharika

**Comment by rob-p** [comment]
Thanks @nihanasam8,

  Please keep me posted and let us know if we can help in any way.  Having not used lambda before, I am not very familiar with the deployment.  Do you have a sense of how much memory is allocated to each node?  Could it be a memory error?  From what little I understand about the setup, the default lambda memory allocations are quite small (128MB), and you have to request a larger allocation for your lambda (up to 10G, which should be more than sufficient for piscem mapping against the transcriptome / genome). How large is your piscem index?  The size on disk should be close to that in RAM.

Best,
Rob

**Comment by nihanasam8** [comment]
Hi Rob,

I have already increased the memory to be 10GB for my lambda instance. My piscem index is 187 MB. I have extracted the transcriptome from the reference genome and generated teh transcriptome to gene mapping file. Sure I will keep you updated once i receive a response from the AWS Team. Thanks for your prompt response and support. 

Thanks,
Niharika

**Comment by patha454** [comment]
Hi @nihanasam8 

`piscem-cpp` builds with `-march=native` by default. `-march=native` is a very aggressive option which produces a binary using any and all features of the building computer's CPU, which may not be present on other CPUs or virtual CPUs - such as Lambda's.

https://github.com/COMBINE-lab/piscem-cpp/blob/2ae91fe4462a0d1c441926e81485dea57f5ccc41/CMakeLists.txt#L46C1-L46C60

Have you tried enabling Conda build, to produce a more portable binary? That'd involve setting the environment variable `CONDA_BUILD=TRUE`, before your run the `piscern` build: https://github.com/COMBINE-lab/piscem/blob/main/build.rs#L7

Arguably Piscern shouldn't use `-march=native` by default - and should only expose the option as an opt-in extra for people who know they'll be running on the same, or a compatible, CPU.

**Comment by nihanasam8** [comment]
Hi Partha,

I have tried building piscem with CONDA_BUILD=TRUE and I'm still facing the same issue.

Thanks,
Niharika

**Comment by patha454** [comment]
Cheers @nihanasam8.

The "Rust cannot catch foreign exceptions" error is a catch-all, which happens when an error happens outside the Rust code - probably in the `piscem-cpp` C++ code.

Are you able to modify your Lambda to build/use `piscem-cpp` directly? That should give us some more specific debug information, rather than the generic error message

**Comment by patha454** [comment]
Oh, @nihanasam8, are you able to share exactly how you're building your Lambda - A dockerfile or shell script what what you've tried so far?

**Comment by patha454** [comment]
One more thing (I promise) @nihanasam8... Are you using an Graviton (ARM) Lambda, or an x86 Lambda?

**Comment by nihanasam8** [comment]
Hi Patha,

Piscem map is running successfully on Lambda. The issue was the location where the output map files are generated. Inside a container, lambda has read only access to all the folders. It can write only to /tmp folder. After changing the output path everything is working as expected.

I'm currently using x86 Lambda. I'm running Lambda using a Docker image by uploading it to AWS ECR.  I compiled piscem by setting the CONDA_BUILD flag as TRUE.

Thankyou so much for all your inputs and actively responding to my queries. This issue can now be closed.

Thanks,
Niharika

**Comment by patha454** [comment]
I'm glad to hear you solved it, Niharika!
